### ISSUE TITLE
About PS2 "Attack of the Toybots"

### ISSUE THREAD

**Issue by rufotheone-fr** [unexpectedpanda/retool-clonelists-metadata#12]
`Nicktoons - Attack of the Toybots` is an english only release for the PAL zone (both EU and AUS) but `Nickelodeon SpongeBob and Friends - Attack of the Toybots` is a Multi6 release for Europe (no Australia but it's exactly the same game, minus the title screen). Retool only takes the `Nicktoons` instead of the other one with the previous setting (treating `Nickelodeon SpongeBob and Friends - Attack of the Toybots` as a regional equivalent)... What I'm trying to do here, by putting 0 in the line of `Nickelodeon SpongeBob and Friends - Attack of the Toybots` is to give this release the priority because any PAL player can give this one a go instead of `Nicktoons` which is english only.

**Comment by rufotheone-fr** [comment]
Probably the same issue.
Within the Wii clonelist `Disney Think Fast - The Quiz Game (Europe) (Fr,Nl)` isn't prefered over `Disney Think Fast (Europe)` when putting France at the top of the list.

**Comment by unexpectedpanda** [comment]
Thanks for this! Pretty sure there are more examples of these on the Retool GitHub page, I'll make sure to test against them as I'm tweaking region and language selection.

Thankfully I can confirm that v2 already selects the following with France at the top of the list:
* **1G1R title:** Nickelodeon SpongeBob and Friends - Attack of the Toybots (Europe) (En,Fr,De,Es,It,Nl)
  * **Clone:** Nicktoons - Attack of the Toybots (Europe, Australia)
* **1G1R title:** Disney Think Fast (Europe) (Fr,De,Nl)
  * **Clone:** Disney Otvechaj - ne zevaj! (Russia)
  * **Clone:** Disney Think Fast (Europe)
  * **Clone:** Disney Think Fast (Europe) (Es,It)
  * **Clone:** Disney Think Fast (USA)

**Comment by unexpectedpanda** [comment]
v2 is now out :)

You'll be happy to know it also addresses your Persona 3 FES selection issue. Finally! 😁
