### ISSUE TITLE
SNES Super Mario World and Allstars

### ISSUE THREAD

**Issue by taalas** [unexpectedpanda/retool-clonelists-metadata#15]
Hi,

I was wondering what the reasoning was, to fulfill Super Mario World and Allstars using the combined rom.

```
		"Super Mario World": [
			["Super Mario All-Stars + Super Mario World", 0],
			["Super Mario All-Stars and Super Mario World", 0],
			["Super Mario World - Super Mario Bros. 4", 1]
		],
```

It seems to me, that these should be 2 different games (ignoring the fact that Allstars are multiple games on one rom in itself).

Also, the games are not valid for Retroachievements any more, if the combined rom is used.

**Comment by unexpectedpanda** [comment]
Most likely reduced number of files on the disk.

Retroachievements have never been part of Retool's design, as I was only made aware of them relatively recently.

Compilations are an ongoing pain point that I'm trying to resolve for v2, but it's sticky. It sounds like an option for preferring individual titles over compilations would be appreciated.

**Comment by taalas** [comment]
Yes, an option to prefer individual titles over compilations would be great (in my opinion). Although I totally understand that from the collections point of view having the compilations instead seems fine, especially since in this case the compilation's version is newer/improved.

**Comment by rufotheone-fr** [comment]
@unexpectedpanda Maybe we should add a line in the corresponding clonelist to specify if a title is part of a compilation (and what it is)?

**Comment by unexpectedpanda** [comment]
This is the format I'm currently testing in v2:

```
"Hash Blocks": [
	{"title": "Hash Blocks"},
	{"compilation": "4 in 1 - Hash Block + Challenger Tank + Brain Power + Jacky Lucky", "title_position": 1},
	{"compilation": "2 in 1 - Hash Blocks + Eagle Plan", "title_position": 1}
	],
```

I'm still playing with the logic for title selection (this particular problem breaks my brain), but that should make things a little clearer, I hope. Unfortunately comments aren't supported in JSON to record why choices are made. I looked at other formats for a while (YAML, TOML), but JSON ultimately managed to still make the most sense from a readability perspective when things started getting complex.

Potentially I can look into a making a [parser](https://github.com/getify/JSON.minify) part of the build process, but that might involve exposing more of that build process here, on GitHub, I think.

Alternatively a decision log could be kept per game in a wiki or some form of documentation system, with the caveat that a lot of the time I don't remember the original reason decisions were made, and would have to research all over again 😅

**Comment by unexpectedpanda** [comment]
Closing this out as it's resolved in v2. Ultimately keeping the compilation as it's a superset of the two games, not just the same versions.
