### ISSUE TITLE
[Nintendo DS] 100 Classic Book Collection

### ISSUE THREAD

**Issue by noinkling** [unexpectedpanda/retool-clonelists-metadata#23]
This "game" is essentially an e-reader app. While on the surface "100 Classic Book Collection (Europe)" and "100 Classic Books (USA)" seem more-or-less the same, they actually contain different sets of books (even if there is some overlap). I assume the same applies to the other regions to an even greater extent, since they're in different languages. To me, these shouldn't be considered clones of each other since the main content (the books themselves that are available) varies so much. 

See: https://en.wikipedia.org/wiki/100_Classic_Book_Collection

**Comment by unexpectedpanda** [comment]
Thanks for that, I'll check it out when I next update No-Intro.

**Comment by unexpectedpanda** [comment]
Given these do include different books, I'll split them apart. It'll be up to the user to filter by language if they wish.

**Comment by unexpectedpanda** [comment]
Fixed in the latest update.
