### ISSUE TITLE
Same title used for 2 different PS2 games XD

### ISSUE THREAD

**Issue by rufotheone-fr** [unexpectedpanda/retool-clonelists-metadata#28]
Hi UP

Here's something really dumb: "Choro Q HG" is called "Gadget Racers" in US and "Penny Racers" in EU.
BUT "Choro Q HG 3" was cancelled in US but was called... "Gadget Racers" in EU \o/

How can we sort this?

**Comment by unexpectedpanda** [comment]
You'd put something like this in the overrides:

```json
{
  "searchTerm": "Gadget Racers \\(Europe\\).*",
  "nameType": "regex",
  "newGroup": "Gadget Racers Europe"
},
```

This moves all European versions of Gadget Racers (with whatever language variants they have) into their own group called `Gadget Racers Europe`, which takes it out of contention for other comparisons.

And then you'd add something like this in the variants:

```json
{
  "group": "Choro Q HG",
  "titles": [
    {"searchTerm": "Choro Q HG (Jenny Hi-Grade Box)"},
    {"searchTerm": "Gadget Racers"},
    {"searchTerm": "Penny Racers"},
    {"searchTerm": "Choro Q HG", "priority": 2}
  ]
},
```

As the European version of Gadget Racers is already elsewhere, the variants only consider the US version.

I haven't tested this btw, you might have to play around a little yourself to make sure things are working as expected.

You might also find the [new documentation](https://unexpectedpanda.github.io/retool/contribute-clone-lists/) interesting.

**Comment by unexpectedpanda** [comment]
This will be resolved in the next update.
