### ISSUE TITLE
Two issues in Sega Genesis/Megadrive

### ISSUE THREAD

**Issue by Goratrix** [unexpectedpanda/retool-clonelists-metadata#54]
First issue, these are the current no-intro roms for Streets of Rage 2:

Bare Knuckle II (Japan) (Beta)
Streets of Rage 2 (USA)
Streets of Rage II (Japan, Europe) (En,Ja)

but second one (Streets of Rage II) is missing in clone list and doesn't get correctly excluded on default settings.

Second issue, NHL '94 has these roms:

NHL '94 (USA, Europe)
NHL '94 (USA, Europe) (Re-release)

The 'Re-release' should get excluded, but both these roms remain in the dat on default settings. According to the no-intro details, the 'Re-release' is an inferior version.

**Comment by unexpectedpanda** [comment]
Thanks! Handled in the recent update.
