### ISSUE TITLE
Small issues in Sega - Mega Drive - Genesis

### ISSUE THREAD

**Issue by Goratrix** [unexpectedpanda/retool-clonelists-metadata#59]
Settings I'm using is exclude everything except 'Games', all other settings on default.

First issue, the following are not getting filtered properly to only 1 rom:

        Bomber (Europe) (Sega Reactor)
        Bomber (USA) (Sega Gopher)
        
        Phantasy Star II - Kaerazaru Toki no Owari ni (Japan) (Mega Drive Mini 2)
        Phantasy Star II (USA, Europe) (Rev A)
        Phantasy Star II (USA, Europe) (Rev A) (Mega Drive Mini 2, Genesis Mini 2)
        
        Star Mobile (Japan) (Mega Drive Mini 2)
        Star Mobile (USA, Europe) (Mega Drive Mini 2, Genesis Mini 2)
        
        Truxton (World)
        Truxton (World) (Mega Drive Mini 2, Genesis Mini 2)
        
        VS Puyo Puyo Sun (Japan) (Mega Drive Mini 2)
        VS Puyo Puyo Sun (USA, Europe) (Mega Drive Mini 2, Genesis Mini 2)

Second issue, Tetris is being filtered to only 1 rom, however there are actually two separate ports.

According to https://segaretro.org/Tetris: "The Mega Drive Mini also includes this game. However, the version included on the system is not the original Mega Drive release, but a brand new version that is a more faithful recreation of the original System 16 version."

So this is the rom of the original 1989 version:

        Tetris (Japan)

And these are the roms of the new version, and should be treated as separate from the previous one when filtering:

        Tetris (Japan) (Mega Drive Mini)
        Tetris (USA) (Genesis Mini)

**Comment by unexpectedpanda** [comment]
Cheers, I'll look into it. I haven't looked at clone lists since December due to some feature work and real life stuff, so it's not surprising there are changes to take into account. At this rate a realistic estimate is February some time.

**Comment by unexpectedpanda** [comment]
Fixed, thanks. Make sure to update to v2.02.0 before updating your clone lists, as the format has changed.
