### ISSUE TITLE
Small issue in SNES

### ISSUE THREAD

**Issue by Goratrix** [unexpectedpanda/retool-clonelists-metadata#62]
Thank you for the big update and all the work! One small issue remaining in Nintendo - Super Nintendo Entertainment System, missing clone relationship:

```
Gourmet Sentai Barayarou (Japan)
Gourmet Warriors (World) (Aftermarket) (Unl)
Gourmet Warriors (World) (QUByte Classics)
```

**Comment by unexpectedpanda** [comment]
Fixed, thanks!
