### ISSUE TITLE
Special Versions in NEC - PC Engine - TurboGrafx-16

### ISSUE THREAD

**Issue by Goratrix** [unexpectedpanda/retool-clonelists-metadata#70]
These 3 roms should be added into clone list and de-prioritized, as they are cut-down limited versions:

Bomberman '93 - Special Version (Japan)
Gunhed - Special Version (Japan)
Soldier Blade - Special Version (Japan)

as one of them is already handled correctly:

                {
                        "group": "Final Soldier",
                        "titles": [
                                {"searchTerm": "Final Soldier"},
                                {"searchTerm": "Final Soldier - Special Version", "priority": 2}
                        ]
                },

Gunhed should go under the existing Blazing Lazers entry.

Reference: https://shmups.system11.org/viewtopic.php?t=10341

Also, Bomberman - Users Battle (Japan) is similar, cut-down version of Bomberman (Japan).

**Comment by unexpectedpanda** [comment]
Thanks, much appreciated. The changes will be up soon.
