### ISSUE TITLE
[PS2] Growlanser V / Heritage of War, and Guilty Gear X2

### ISSUE THREAD

**Issue by zealvix** [unexpectedpanda/retool-clonelists-metadata#73]
The two games below are the same games in different language/region:
Growlanser - Heritage of War (USA)
Growlanser V - Generations (Japan) (Shokai Genteiban)

I also noticed that all versions of Guilty Gear X2 (https://en.wikipedia.org/wiki/Guilty_Gear_X2_updated_versions) seems to be kept currently. Is that intended due to minor differences between the versions?

**Comment by unexpectedpanda** [comment]
> Growlanser - Heritage of War (USA)
> Growlanser V - Generations (Japan) (Shokai Genteiban)

Cheers!

> I also noticed that all versions of Guilty Gear X2 (https://en.wikipedia.org/wiki/Guilty_Gear_X2_updated_versions) seems to be kept currently. Is that intended due to minor differences between the versions?

It's a longstanding tradition of generally not touching fighting games. Everything seems to be a rebalance with each revision, so I'm not game to wade into that particular pond.

Perhaps it's something I can along with [#236](https://github.com/unexpectedpanda/retool/issues/236), if I ever do it.

**Comment by unexpectedpanda** [comment]
Clone lists have been updated, thanks again :)
